require 'rake/testtask'
require 'rspec/core/rake_task'
require 'rubocop'
require 'rubocop/rake_task'
require 'rubocop-rake'

task :default => [:spec]

Rake::TestTask.new do |t|
  t.pattern = "*/tests/test_*.rb"
  t.verbose = true
  t.warning = false
end

desc "Run the specs."
RSpec::Core::RakeTask.new do |t|
  t.pattern = "iam/spec/*_spec.rb"
end

desc "Run the coverage report."
RSpec::Core::RakeTask.new(:coverage) do |t|
  t.pattern = "iam/spec/*_spec.rb"
  require 'simplecov'
  SimpleCov.start
end

desc 'Run rubocop'
RuboCop::RakeTask.new(:rubocop) do |t|
  t.options = ['--config', '../../.github/linters/.ruby-lint.yml']
  t.requires << 'rubocop-rake'
end

#
# require 'simplecov'
# SimpleCov.start
